name: semgrep-scanner benchmarks

on:
  workflow_dispatch:
  push:
    branches: [release]
  pull_request:
    branches: [develop, release]
jobs:
  trigger:
    # do not run automatically if rule is posted from the playground (can still be started manually)
    # PRs posted by first time contributors already need approval as well
    if: github.actor != 'semgrep-dev-pr-bot'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: changed-files
        name: get changed files
        env:
          HEAD_REF: ${{ github.head_ref }}
          BASE_REF: ${{ github.base_ref }}
        run: |
          echo "::set-output name=CHANGED_FILES::$(git diff --name-only origin/${BASE_REF} origin/${HEAD_REF} | xargs )"
      - id: changed-langs
        name: get changed langs
        env:
          HEAD_REF: ${{ github.head_ref }}
          BASE_REF: ${{ github.base_ref }}
        run: |
          echo "::set-output name=CHANGED_LANGS::$(git diff --name-only origin/${BASE_REF} origin/${HEAD_REF} | xargs -0 | awk -F/ '{print $1}' | sed -E '/^$|.github|bash|contrib|fingerprints|generic|json|problem-based-packs|scripts|stats|trusted_python|yaml/d' )"
      - id: print-changed-files
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.CHANGED_FILES }}
        name: debugging step - print changed files
        run: echo $CHANGED_FILES
      - id: print-changed-langs
        env:
          CHANGED_LANGS: ${{ steps.changed-langs.outputs.CHANGED_LANGS }}
        name: debugging step - print changed langs
        run: echo $CHANGED_LANGS
      - name: Trigger semgrep-scanner argo workflow on push to release
        if: github.event_name == 'push'
        run: |
            curl -X POST https://argo.corp.r2c.dev/api/v1/events/security-research/initiate-scan -H "Authorization: ${{ secrets.ARGO_WORKFLOWS_TOKEN }}" -d "{\"branch\" : \"${{github.ref}}\", \"repo\" : \"semgrep-rules\", \"pull_request\" : \"0000\", \"post_back\" : false }"
      - name: Trigger semgrep-scanner argo workflow on PR to develop or release
        if: github.event_name == 'pull_request'
        run: |
          curl -X POST https://argo.corp.r2c.dev/api/v1/events/security-research/initiate-scan-argo -H "Authorization: ${{ secrets.ARGO_WORKFLOWS_TOKEN }}" -d "{\"branch\" : \"${{github.head_ref}}\", \"repo\" : \"${{github.event.repository.name}}\", \"commit\" : \"${{github.event.pull_request.head.sha}}\", \"changed_files\" : \"$CHANGED_FILES\"}"
